import type { CategoryConfig } from '../../product/types.js';

/** 商品类别配置 - 20个大类（v1.1 扩展版） */
export const categoryConfigs: CategoryConfig[] = [
  {
    id: '数码科技', label: '数码科技', icon: '📱',
    description: '包括手机、耳机、平板、电脑、智能穿戴等消费电子产品',
    recommendedFamilies: ['TechClean', 'TechPremium'],
    recommendedStyles: ['科技简洁', '科技高端'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '冷色调科技蓝',
    recommendedStructure: '痛点→产品亮相→参数卖点→场景→CTA',
    avoidFamilies: ['SoftBeauty', 'BabyCare', 'PetFriendly'],
    exampleProducts: ['蓝牙耳机', '智能手表', '机械键盘', '充电宝', '平板电脑'],
    sampleProducts: ['无线降噪耳机', '智能手环', '便携投影仪', '氮化镓充电器'],
    riskNotes: '不得虚假宣传参数，续航/性能数据需有依据',
  },
  {
    id: '美妆护肤', label: '美妆护肤', icon: '💄',
    description: '包括护肤品、彩妆、香水、美容工具等个人美妆产品',
    recommendedFamilies: ['SoftBeauty'],
    recommendedStyles: ['美妆柔和'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['品质', '情感', '场景'],
    recommendedCTAStyle: 'slide-up',
    recommendedColorScheme: '柔和粉色调',
    recommendedStructure: '肌肤痛点→产品展示→成分卖点→使用对比→CTA',
    avoidFamilies: ['AutoGear', 'TechClean', 'SportEnergy'],
    exampleProducts: ['护肤精华', '面膜', '口红', '防晒霜', '洗面奶'],
    sampleProducts: ['玻尿酸精华液', '补水面膜', '防晒喷雾', '卸妆油'],
    riskNotes: '⚠️ 不得宣传医疗功效，不得使用"根治""治愈"等医疗用语',
  },
  {
    id: '食品饮料', label: '食品饮料', icon: '🍜',
    description: '包括零食、饮品、生鲜、调味品等食品类产品',
    recommendedFamilies: ['FreshFood', 'BoldPromo', 'FestivalGift'],
    recommendedStyles: ['食品清新', '强促销', '节日礼赠'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['品质', '价格', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '清新绿色或食欲橙色',
    recommendedStructure: '食欲唤起→产品特写→口味/原料卖点→食用场景→CTA',
    avoidFamilies: ['TechPremium', 'AutoGear'],
    exampleProducts: ['即食麦片', '坚果零食', '咖啡豆', '果汁饮料', '速食面'],
    sampleProducts: ['混合坚果礼盒', '即溶咖啡', '有机燕麦片', '水果干'],
    riskNotes: '⚠️ 不得夸大健康效果，不得使用"治病""抗癌"等医疗用语',
  },
  {
    id: '家居日用', label: '家居日用', icon: '🏠',
    description: '包括收纳、清洁、装饰、家纺等日常生活用品',
    recommendedFamilies: ['WarmLifestyle', 'HomeComfort'],
    recommendedStyles: ['生活种草', '家居温馨'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '暖色调米色',
    recommendedStructure: '生活痛点→产品展示→功能卖点→使用场景→CTA',
    avoidFamilies: ['TechPremium', 'AutoGear', 'SportEnergy'],
    exampleProducts: ['收纳盒', '保温杯', '香薰蜡烛', '靠枕', '地毯'],
    sampleProducts: ['折叠收纳盒', '智能保温杯', '无火香薰', '记忆枕'],
    riskNotes: '产品功能描述需真实，不得虚假宣传材质',
  },
  {
    id: '服饰鞋包', label: '服饰鞋包', icon: '👗',
    description: '包括服装、鞋靴、箱包、配饰等穿戴类产品',
    recommendedFamilies: ['FashionLook', 'BoldPromo'],
    recommendedStyles: ['服饰潮流', '强促销'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['品质', '情感', '场景'],
    recommendedCTAStyle: 'banner',
    recommendedColorScheme: '黑白灰为主',
    recommendedStructure: '穿搭场景→产品展示→面料/设计卖点→上身效果→CTA',
    avoidFamilies: ['TechClean', 'FreshFood', 'AutoGear'],
    exampleProducts: ['运动鞋', '连衣裙', '背包', '太阳镜', '手表'],
    sampleProducts: ['飞织跑步鞋', '休闲双肩包', '防晒帽', '运动腰包'],
    riskNotes: '尺码信息需准确，不得使用误导性模特图',
  },
  {
    id: '健身运动', label: '健身运动', icon: '💪',
    description: '包括运动器材、健身装备、运动服饰、营养补剂等',
    recommendedFamilies: ['SportEnergy'],
    recommendedStyles: ['运动活力'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'pulse',
    recommendedColorScheme: '高饱和活力色',
    recommendedStructure: '运动场景→产品展示→性能卖点→使用演示→CTA',
    avoidFamilies: ['SoftBeauty', 'HomeComfort', 'BabyCare'],
    exampleProducts: ['筋膜枪', '瑜伽垫', '运动手环', '蛋白粉', '跑步机'],
    sampleProducts: ['深层按摩筋膜枪', 'TPE瑜伽垫', '运动护膝', '摇摇杯'],
    riskNotes: '营养补剂不得宣传医疗功效',
  },
  {
    id: '母婴用品', label: '母婴用品', icon: '👶',
    description: '包括婴儿食品、婴儿护理、儿童玩具、孕妇用品等',
    recommendedFamilies: ['BabyCare'],
    recommendedStyles: ['母婴安心'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['品质', '功能', '情感'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '柔和马卡龙色',
    recommendedStructure: '宝宝需求→产品展示→安全/材质卖点→使用场景→CTA',
    avoidFamilies: ['BoldPromo', 'AutoGear', 'TechPremium'],
    exampleProducts: ['婴儿湿巾', '奶瓶', '婴儿车', '儿童玩具', '纸尿裤'],
    sampleProducts: ['婴儿纯棉湿巾', 'PPSU奶瓶', '益智积木', '防踢被'],
    riskNotes: '⚠️ 不得承诺"绝对安全""零风险"，安全声明需有检测报告支撑',
  },
  {
    id: '宠物用品', label: '宠物用品', icon: '🐾',
    description: '包括宠物食品、宠物玩具、宠物护理、宠物住所等',
    recommendedFamilies: ['PetFriendly'],
    recommendedStyles: ['宠物亲和'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['品质', '功能', '情感'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '温暖橙色调',
    recommendedStructure: '宠物日常→产品展示→营养/安全卖点→使用场景→CTA',
    avoidFamilies: ['TechPremium', 'AutoGear', 'FashionLook'],
    exampleProducts: ['猫粮', '狗粮', '宠物玩具', '猫砂', '宠物零食'],
    sampleProducts: ['全价猫粮', '冻干零食', '猫抓板', '宠物自动喂食器'],
    riskNotes: '宠物食品成分描述需真实，不得虚假宣传营养成分',
  },
  {
    id: '学习办公', label: '学习办公', icon: '📚',
    description: '包括文具、办公设备、学习工具、办公家具等',
    recommendedFamilies: ['StudyOffice'],
    recommendedStyles: ['学习办公'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '清爽蓝绿色',
    recommendedStructure: '学习/办公痛点→产品展示→效率/功能卖点→使用场景→CTA',
    avoidFamilies: ['BoldPromo', 'SoftBeauty', 'PetFriendly'],
    exampleProducts: ['机械键盘', '台灯', '笔记本', '课程', '办公椅'],
    sampleProducts: ['静音键盘', '护眼台灯', '活页笔记本', '人体工学椅'],
    riskNotes: '产品参数需真实，不得虚假宣传护眼等功能',
  },
  {
    id: '个护健康', label: '个护健康', icon: '🏥',
    description: '包括电动牙刷、按摩仪、保健品、健康监测设备等',
    recommendedFamilies: ['HealthCare'],
    recommendedStyles: ['健康个护'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '清新医疗绿',
    recommendedStructure: '健康痛点→产品展示→成分/效果卖点→使用建议→CTA',
    avoidFamilies: ['BoldPromo', 'FashionLook', 'AutoGear'],
    exampleProducts: ['电动牙刷', '按摩仪', '维生素', '护眼灯', '空气净化器'],
    sampleProducts: ['声波电动牙刷', '颈椎按摩仪', '复合维生素', '空气净化器'],
    riskNotes: '⚠️ 保健品不得宣传医疗功效，不得使用"治疗""治愈"等用语',
  },
  {
    id: '汽车用品', label: '汽车用品', icon: '🚗',
    description: '包括车载设备、汽车配件、汽车装饰、车载清洁等',
    recommendedFamilies: ['AutoGear'],
    recommendedStyles: ['汽车用品'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '深色金属质感',
    recommendedStructure: '用车痛点→产品展示→性能参数卖点→安装演示→CTA',
    avoidFamilies: ['SoftBeauty', 'BabyCare', 'PetFriendly', 'HomeComfort'],
    exampleProducts: ['车载吸尘器', '行车记录仪', '车载充电器', '汽车脚垫', '遮阳帘'],
    sampleProducts: ['无线车载吸尘器', '4K行车记录仪', '车载无线充电器', '全包围脚垫'],
    riskNotes: '车载产品需标注适用型号，不得虚假宣传兼容性',
  },
  {
    id: '节日礼品', label: '节日礼品', icon: '🎁',
    description: '包括节日礼盒、礼品套装、鲜花、定制礼品等',
    recommendedFamilies: ['FestivalGift'],
    recommendedStyles: ['节日礼赠'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['情感', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '喜庆红金色',
    recommendedStructure: '送礼场景→礼盒展示→情感卖点→包装细节→CTA',
    avoidFamilies: ['AutoGear', 'TechClean', 'SportEnergy'],
    exampleProducts: ['节日礼盒', '茶叶礼盒', '巧克力礼盒', '鲜花', '红包套装'],
    sampleProducts: ['中秋月饼礼盒', '精品茶叶礼盒', '手工巧克力礼盒', '永生花礼盒'],
    riskNotes: '食品类礼品需标注保质期和成分',
  },
  {
    id: '厨房用品', label: '厨房用品', icon: '🍳',
    description: '包括厨具、餐具、厨房收纳、烘焙工具等',
    recommendedFamilies: ['WarmLifestyle', 'FreshFood', 'HomeComfort'],
    recommendedStyles: ['生活种草', '食品清新', '家居温馨'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '暖色调',
    recommendedStructure: '烹饪场景→产品展示→功能卖点→使用演示→CTA',
    avoidFamilies: ['AutoGear', 'FashionLook', 'BabyCare'],
    exampleProducts: ['不粘锅', '料理机', '厨房收纳', '刀具套装', '空气炸锅'],
    sampleProducts: ['麦饭石不粘锅', '多功能料理机', '厨房置物架', '陶瓷刀套装'],
    riskNotes: '厨具材质描述需真实，不得虚假宣传不粘性能',
  },
  {
    id: '旅行户外', label: '旅行户外', icon: '🏕️',
    description: '包括户外装备、旅行用品、露营设备、户外服饰等',
    recommendedFamilies: ['SportEnergy', 'WarmLifestyle'],
    recommendedStyles: ['运动活力', '生活种草'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '自然绿色活力色',
    recommendedStructure: '户外场景→产品展示→功能/便携卖点→使用演示→CTA',
    avoidFamilies: ['SoftBeauty', 'BabyCare', 'HomeComfort'],
    exampleProducts: ['帐篷', '登山包', '保温壶', '户外灯具', '便携椅'],
    sampleProducts: ['自动帐篷', '登山双肩包', '不锈钢保温壶', 'LED露营灯'],
    riskNotes: '户外装备需标注适用环境和承重等参数',
  },
  {
    id: '家电电器', label: '家电电器', icon: '🔌',
    description: '包括厨房电器、清洁电器、生活电器、环境电器等',
    recommendedFamilies: ['TechClean', 'WarmLifestyle', 'HomeComfort'],
    recommendedStyles: ['科技简洁', '生活种草', '家居温馨'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '科技蓝或暖色调',
    recommendedStructure: '生活痛点→产品展示→功能/能效卖点→使用场景→CTA',
    avoidFamilies: ['FashionLook', 'PetFriendly', 'BabyCare'],
    exampleProducts: ['扫地机器人', '空气净化器', '电饭煲', '破壁机', '烘干机'],
    sampleProducts: ['智能扫地机器人', '空气净化器', 'IH电饭煲', '多功能破壁机'],
    riskNotes: '能效标识需真实，产品参数不得虚假宣传',
  },
  {
    id: '珠宝配饰', label: '珠宝配饰', icon: '💎',
    description: '包括项链、手链、戒指、耳饰、发饰等装饰品',
    recommendedFamilies: ['SoftBeauty', 'FashionLook', 'FestivalGift'],
    recommendedStyles: ['美妆柔和', '服饰潮流', '节日礼赠'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['品质', '情感', '场景'],
    recommendedCTAStyle: 'slide-up',
    recommendedColorScheme: '优雅金色或银色',
    recommendedStructure: '佩戴场景→产品特写→工艺/材质卖点→搭配效果→CTA',
    avoidFamilies: ['BoldPromo', 'AutoGear', 'SportEnergy'],
    exampleProducts: ['银项链', '珍珠耳环', '手链', '发夹', '胸针'],
    sampleProducts: ['925银项链', '淡水珍珠耳环', '编织手链', '合金发夹'],
    riskNotes: '材质描述需真实，不得以次充好，需标注材质成分',
  },
  {
    id: '虚拟课程', label: '虚拟课程', icon: '🎓',
    description: '包括在线课程、知识付费、培训教程、电子书等虚拟产品',
    recommendedFamilies: ['StudyOffice'],
    recommendedStyles: ['学习办公'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '情感', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '清爽蓝色',
    recommendedStructure: '学习痛点→课程亮点→讲师/内容卖点→学员评价→CTA',
    avoidFamilies: ['BoldPromo', 'FreshFood', 'AutoGear', 'PetFriendly'],
    exampleProducts: ['编程课程', '英语课程', '设计课程', '理财课程', '考证培训'],
    sampleProducts: ['Python入门课程', '商务英语课程', 'UI设计课程', '理财基础课'],
    riskNotes: '不得承诺"包过""保证就业"等效果，课程内容描述需真实',
  },
  {
    id: '软件工具', label: '软件工具', icon: '🖥️',
    description: '包括效率工具、设计软件、开发工具、SaaS服务等',
    recommendedFamilies: ['TechClean', 'StudyOffice'],
    recommendedStyles: ['科技简洁', '学习办公'],
    recommendedVideoDurations: [30, 45],
    recommendedSellingPointTypes: ['功能', '场景', '价格'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '科技蓝',
    recommendedStructure: '效率痛点→功能展示→使用场景→效率对比→CTA',
    avoidFamilies: ['SoftBeauty', 'FreshFood', 'BabyCare', 'PetFriendly'],
    exampleProducts: ['笔记软件', '设计工具', '项目管理', 'AI写作助手', '剪辑软件'],
    sampleProducts: ['云端笔记工具', '在线设计平台', '团队协作工具', 'AI翻译助手'],
    riskNotes: '功能描述需与实际版本一致，不得虚假宣传AI能力',
  },
  {
    id: '图书文创', label: '图书文创', icon: '📖',
    description: '包括图书、文具、创意礼品、手账用品等文化产品',
    recommendedFamilies: ['StudyOffice', 'WarmLifestyle', 'FestivalGift'],
    recommendedStyles: ['学习办公', '生活种草', '节日礼赠'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['情感', '品质', '场景'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '文艺暖色调',
    recommendedStructure: '阅读/创作场景→产品展示→内容/工艺卖点→使用场景→CTA',
    avoidFamilies: ['AutoGear', 'BoldPromo', 'SportEnergy'],
    exampleProducts: ['畅销书', '手账本', '钢笔', '创意书签', '明信片套装'],
    sampleProducts: ['畅销小说', 'A5手账本', '钢笔礼盒', '创意冰箱贴'],
    riskNotes: '图书内容介绍需准确，不得虚假宣传销量',
  },
  {
    id: '本地生活服务', label: '本地生活服务', icon: '🏪',
    description: '包括餐饮、美容、健身、家政、维修等本地服务',
    recommendedFamilies: ['WarmLifestyle', 'BoldPromo', 'SportEnergy'],
    recommendedStyles: ['生活种草', '强促销', '运动活力'],
    recommendedVideoDurations: [15, 30],
    recommendedSellingPointTypes: ['场景', '价格', '情感'],
    recommendedCTAStyle: 'button',
    recommendedColorScheme: '活力暖色调',
    recommendedStructure: '服务场景→服务展示→价格/优惠→用户评价→CTA',
    avoidFamilies: ['TechPremium', 'AutoGear'],
    exampleProducts: ['美容SPA', '健身房月卡', '家政保洁', '宠物寄养', '摄影套餐'],
    sampleProducts: ['面部护理套餐', '健身房季卡', '深度保洁服务', '宠物洗澡套餐'],
    riskNotes: '服务描述需真实，价格和有效期需明确标注',
  },
];

/** 按类别 ID 获取配置 */
export function getCategoryConfig(id: string): CategoryConfig | undefined {
  return categoryConfigs.find((c) => c.id === id);
}

/** 获取所有类别 */
export function getAllCategories(): CategoryConfig[] {
  return categoryConfigs;
}
