import type { TemplateFamily, TypographyScale } from '../types.js';

/** 通用字体配置 */
const sansSerif: TypographyScale = {
  titleSize: 56, subtitleSize: 32, bodySize: 24, captionSize: 18, ctaSize: 28,
  titleWeight: 700, fontFamily: '"PingFang SC", "Microsoft YaHei", sans-serif',
};

const elegantSerif: TypographyScale = {
  titleSize: 52, subtitleSize: 30, bodySize: 22, captionSize: 16, ctaSize: 26,
  titleWeight: 600, fontFamily: '"Noto Serif SC", "SimSun", serif',
};

const boldSans: TypographyScale = {
  titleSize: 64, subtitleSize: 36, bodySize: 26, captionSize: 20, ctaSize: 32,
  titleWeight: 800, fontFamily: '"PingFang SC", "Microsoft YaHei", sans-serif',
};

/** 15 个模板家族定义 - 增强版 */
export const templateFamilies: TemplateFamily[] = [
  {
    id: 'TechClean',
    name: '科技简洁风',
    nameEn: 'Tech Clean',
    description: '以极简线条和冷色调为主，适合数码3C、智能硬件等科技产品，强调产品本身的设计感和技术参数。',
    suitableCategories: ['数码科技', '学习办公'],
    suitableGoals: ['讲解', '品牌', '新品发布'],
    colorTheme: { primary: '#0066FF', secondary: '#E8F0FE', accent: '#00D4AA', background: '#F8FAFB', surface: '#FFFFFF', text: '#1A1A2E', textSecondary: '#6B7280' },
    typography: sansSerif,
    visualDensity: '极简',
    motionIntensity: '标准',
    icon: '💻',
    recommendedScenarios: ['新品发布会', '产品测评', '功能讲解', '开箱体验'],
    recommendedProductTypes: ['蓝牙耳机', '智能手表', '平板电脑', '充电宝', '机械键盘', '显示器'],
    recommendedVideoStructure: ['痛点引入', '产品亮相', '核心参数展示', '使用场景', '对比优势', 'CTA'],
    recommendedCTAs: ['了解更多', '立即抢购', '限时优惠', '新品尝鲜'],
    colorDescription: '冷色调科技蓝为主，搭配浅灰背景，营造专业理性的科技感',
    rhythmDescription: '中等节奏，每个场景停留2-4秒，转场使用淡入淡出或滑动',
    recommendedCaptionStyle: '简洁白色字幕条，底部居中，无过多装饰',
  },
  {
    id: 'TechPremium',
    name: '科技高端风',
    nameEn: 'Tech Premium',
    description: '深色背景配金属质感高光，适合高端数码、奢侈品级电子产品，营造尊贵和前沿感。',
    suitableCategories: ['数码科技'],
    suitableGoals: ['品牌', '新品发布'],
    colorTheme: { primary: '#C9A96E', secondary: '#1A1A2E', accent: '#E8D5B5', background: '#0D0D1A', surface: '#1A1A2E', text: '#F5F5F5', textSecondary: '#A0A0B0', gradient: 'linear-gradient(135deg, #0D0D1A 0%, #1A1A2E 50%, #2D1B4E 100%)' },
    typography: { ...elegantSerif, titleSize: 58 },
    visualDensity: '极简',
    motionIntensity: '舒缓',
    icon: '🏆',
    recommendedScenarios: ['品牌宣传片', '旗舰新品发布', '高端体验展示', '品牌故事'],
    recommendedProductTypes: ['旗舰手机', '高端耳机', '专业相机', '智能音箱', '高端显示器'],
    recommendedVideoStructure: ['品牌氛围开场', '产品轮廓渐显', '工艺细节特写', '使用场景渲染', '品牌宣言', 'CTA'],
    recommendedCTAs: ['探索更多', '尊享体验', '立即预约', '限量发售'],
    colorDescription: '深色背景搭配金色/香槟色点缀，营造高端奢华质感',
    rhythmDescription: '舒缓优雅节奏，场景切换缓慢，多用溶解和渐变转场',
    recommendedCaptionStyle: '半透明深色底衬，金色或白色文字，衬线字体',
  },
  {
    id: 'WarmLifestyle',
    name: '生活种草风',
    nameEn: 'Warm Lifestyle',
    description: '暖色调、生活场景化，适合日用百货、家居好物、生活小物，营造真实使用感和信任感。',
    suitableCategories: ['家居日用', '厨房用品', '户外旅行'],
    suitableGoals: ['种草', '新品发布'],
    colorTheme: { primary: '#FF8C42', secondary: '#FFF3E8', accent: '#FF6B6B', background: '#FFFAF5', surface: '#FFFFFF', text: '#2D2D2D', textSecondary: '#888888' },
    typography: sansSerif,
    visualDensity: '标准',
    motionIntensity: '舒缓',
    icon: '🏠',
    recommendedScenarios: ['日常好物推荐', '家居改造', '生活小窍门', '收纳整理'],
    recommendedProductTypes: ['收纳盒', '保温杯', '香薰蜡烛', '靠枕', '地毯', '厨房小工具'],
    recommendedVideoStructure: ['生活痛点引入', '产品出场', '使用场景展示', '前后对比', '用户好评', 'CTA'],
    recommendedCTAs: ['把好物带回家', '立即下单', '限时特惠', '生活升级'],
    colorDescription: '暖橙色为主色调，米白色背景，营造温馨舒适的生活氛围',
    rhythmDescription: '舒缓自然节奏，模拟真实生活记录感，转场柔和',
    recommendedCaptionStyle: '暖色系字幕，圆角卡片样式，带小图标点缀',
  },
  {
    id: 'SoftBeauty',
    name: '美妆柔和风',
    nameEn: 'Soft Beauty',
    description: '柔和粉色调、精致排版，适合美妆护肤、香水、饰品等女性向产品，强调质感和美感。',
    suitableCategories: ['美妆护肤'],
    suitableGoals: ['种草', '品牌'],
    colorTheme: { primary: '#E8739E', secondary: '#FFF0F5', accent: '#FFB6C1', background: '#FFF8FB', surface: '#FFFFFF', text: '#4A3040', textSecondary: '#B08090' },
    typography: elegantSerif,
    visualDensity: '标准',
    motionIntensity: '舒缓',
    icon: '💄',
    recommendedScenarios: ['美妆教程', '护肤科普', '产品种草', '成分解析', '妆容展示'],
    recommendedProductTypes: ['精华液', '面膜', '口红', '防晒霜', '香水', '眼影盘'],
    recommendedVideoStructure: ['肌肤/妆容痛点', '产品精致展示', '成分/质地讲解', '使用前后对比', '效果展示', 'CTA'],
    recommendedCTAs: ['解锁美丽', '立即拥有', '限时体验', '美丽不等待'],
    colorDescription: '柔和粉色系为主，搭配浅紫和米白，营造精致优雅的女性美感',
    rhythmDescription: '舒缓优雅节奏，场景停留稍长以展示产品质感，转场柔和',
    recommendedCaptionStyle: '精致卡片字幕，粉色或淡紫色衬底，衬线字体',
  },
  {
    id: 'BoldPromo',
    name: '强促销风',
    nameEn: 'Bold Promo',
    description: '高对比度、大字号价格、闪烁动效，适合促销活动、限时折扣、清仓甩卖，营造紧迫感。',
    suitableCategories: ['食品饮料', '服饰鞋包', '家居日用'],
    suitableGoals: ['促销', '节日营销'],
    colorTheme: { primary: '#FF2D2D', secondary: '#FFEBE8', accent: '#FFD700', background: '#FFF5F5', surface: '#FFFFFF', text: '#1A1A1A', textSecondary: '#666666' },
    typography: boldSans,
    visualDensity: '信息强化',
    motionIntensity: '快节奏',
    icon: '🔥',
    recommendedScenarios: ['限时秒杀', '直播间促销', '清仓甩卖', '节日大促', '满减活动'],
    recommendedProductTypes: ['零食礼盒', '日用百货', '服装鞋帽', '家居清洁', '小家电'],
    recommendedVideoStructure: ['紧迫感开场', '价格震撼展示', '产品快速展示', '限时优惠信息', '倒计时催促', 'CTA'],
    recommendedCTAs: ['🔥 限时秒杀', '手慢无', '立即抢购', '错过等一年'],
    colorDescription: '高对比红黄配色，价格用大字号金色展示，营造紧迫促销感',
    rhythmDescription: '快节奏，场景切换迅速（1-2秒），配合闪烁和放大动效',
    recommendedCaptionStyle: '高对比度字幕，价格用大字号红色高亮，带闪烁动效',
  },
  {
    id: 'FreshFood',
    name: '食品清新风',
    nameEn: 'Fresh Food',
    description: '清新绿色调、食欲感配色，适合食品饮料、生鲜水果、零食特产，营造新鲜健康感。',
    suitableCategories: ['食品饮料', '厨房用品'],
    suitableGoals: ['种草', '促销'],
    colorTheme: { primary: '#4CAF50', secondary: '#E8F5E9', accent: '#FF9800', background: '#FAFFF8', surface: '#FFFFFF', text: '#2E3A2E', textSecondary: '#7A8A7A' },
    typography: sansSerif,
    visualDensity: '标准',
    motionIntensity: '标准',
    icon: '🥗',
    recommendedScenarios: ['美食制作过程', '食材展示', '口味测评', '健康饮食推荐'],
    recommendedProductTypes: ['坚果零食', '即食麦片', '咖啡豆', '果汁饮料', '调味品', '水果生鲜'],
    recommendedVideoStructure: ['食欲唤起开场', '产品/食材特写', '制作/食用过程', '口味/营养卖点', '食用场景', 'CTA'],
    recommendedCTAs: ['尝鲜价', '立即下单', '新鲜到家', '今日特惠'],
    colorDescription: '清新绿色搭配暖橙色点缀，营造新鲜健康的食欲感',
    rhythmDescription: '中等节奏，食材展示时稍慢以突出质感，制作过程可加快',
    recommendedCaptionStyle: '清新绿色系字幕条，圆角设计，带食材小图标',
  },
  {
    id: 'HomeComfort',
    name: '家居温馨风',
    nameEn: 'Home Comfort',
    description: '米色暖调、柔和光影，适合家居家纺、收纳整理、装饰摆件，营造温馨居家感。',
    suitableCategories: ['家居日用', '厨房用品'],
    suitableGoals: ['种草', '品牌'],
    colorTheme: { primary: '#B8860B', secondary: '#FFF8E7', accent: '#D4A574', background: '#FFFCF5', surface: '#FFFFFF', text: '#3E3228', textSecondary: '#9A8A7A' },
    typography: elegantSerif,
    visualDensity: '极简',
    motionIntensity: '舒缓',
    icon: '🛋️',
    recommendedScenarios: ['家居改造', '收纳整理', '房间布置', '生活品质提升'],
    recommendedProductTypes: ['收纳柜', '香薰灯', '床品四件套', '窗帘', '装饰画', '花瓶'],
    recommendedVideoStructure: ['温馨家居场景', '产品融入展示', '功能/材质讲解', '使用前后对比', '生活方式渲染', 'CTA'],
    recommendedCTAs: ['让家更温馨', '立即升级', '品质生活', '限时优惠'],
    colorDescription: '米色和暖棕色为主，搭配柔和光影，营造温馨居家氛围',
    rhythmDescription: '舒缓慢节奏，大量留白，场景转换使用溶解效果',
    recommendedCaptionStyle: '米色衬底字幕，优雅衬线字体，简约不抢眼',
  },
  {
    id: 'FashionLook',
    name: '服饰潮流风',
    nameEn: 'Fashion Look',
    description: '黑白灰为主、大图展示，适合服饰鞋包、配饰、潮牌，强调穿搭效果和潮流感。',
    suitableCategories: ['服饰鞋包'],
    suitableGoals: ['种草', '品牌'],
    colorTheme: { primary: '#1A1A1A', secondary: '#F5F5F5', accent: '#FF4081', background: '#FAFAFA', surface: '#FFFFFF', text: '#1A1A1A', textSecondary: '#888888' },
    typography: boldSans,
    visualDensity: '极简',
    motionIntensity: '标准',
    icon: '👗',
    recommendedScenarios: ['穿搭展示', '新品上市', '街拍风格', '季节换装'],
    recommendedProductTypes: ['连衣裙', '运动鞋', '手提包', '太阳镜', '手表', '围巾'],
    recommendedVideoStructure: ['穿搭场景开场', '产品特写展示', '面料/设计细节', '上身/搭配效果', '风格宣言', 'CTA'],
    recommendedCTAs: ['解锁穿搭', '立即入手', '限时上新', '潮流必备'],
    colorDescription: '黑白灰为主色调，偶尔点缀亮色（如粉色），营造高级潮流感',
    rhythmDescription: '中等偏快节奏，配合街拍感的快速切换和定格',
    recommendedCaptionStyle: '极简黑白字幕，无衬线粗体，突出潮流态度',
  },
  {
    id: 'SportEnergy',
    name: '运动活力风',
    nameEn: 'Sport Energy',
    description: '高饱和度、动感配色，适合运动健身、户外装备、能量饮料，营造活力和冲劲。',
    suitableCategories: ['健身运动', '户外旅行'],
    suitableGoals: ['种草', '促销', '新品发布'],
    colorTheme: { primary: '#FF5722', secondary: '#FFF3E0', accent: '#00E5FF', background: '#FFFBF5', surface: '#FFFFFF', text: '#1A1A1A', textSecondary: '#666666' },
    typography: boldSans,
    visualDensity: '标准',
    motionIntensity: '快节奏',
    icon: '💪',
    recommendedScenarios: ['运动场景', '健身训练', '户外探险', '运动装备测评'],
    recommendedProductTypes: ['筋膜枪', '瑜伽垫', '运动手环', '跑步鞋', '蛋白粉', '运动水壶'],
    recommendedVideoStructure: ['运动场景开场', '产品展示', '性能/功能卖点', '使用演示', '运动效果', 'CTA'],
    recommendedCTAs: ['燃起来', '立即装备', '限时特惠', '挑战极限'],
    colorDescription: '高饱和橙红色为主，搭配活力蓝绿色点缀，营造运动激情',
    rhythmDescription: '快节奏动感，场景快速切换，配合运动感的放大和滑动转场',
    recommendedCaptionStyle: '粗体无衬线字幕，高对比度，带运动感的斜体或下划线',
  },
  {
    id: 'BabyCare',
    name: '母婴安心风',
    nameEn: 'Baby Care',
    description: '柔和马卡龙色、圆润造型，适合母婴用品、婴儿食品、儿童玩具，营造安全放心感。',
    suitableCategories: ['母婴用品'],
    suitableGoals: ['种草', '品牌'],
    colorTheme: { primary: '#7E57C2', secondary: '#F3E5F5', accent: '#FF8A80', background: '#FFFBFE', surface: '#FFFFFF', text: '#3E2A4A', textSecondary: '#9A80A0' },
    typography: { ...sansSerif, titleWeight: 600 },
    visualDensity: '标准',
    motionIntensity: '舒缓',
    icon: '👶',
    recommendedScenarios: ['宝宝日常', '育儿好物', '婴儿护理', '亲子互动'],
    recommendedProductTypes: ['婴儿湿巾', '奶瓶', '婴儿车', '儿童玩具', '纸尿裤', '婴儿服装'],
    recommendedVideoStructure: ['宝宝需求场景', '产品安全展示', '材质/成分讲解', '使用场景', '妈妈好评', 'CTA'],
    recommendedCTAs: ['守护宝宝', '安心之选', '限时优惠', '妈妈放心选'],
    colorDescription: '柔和马卡龙色系（淡紫、淡粉、淡蓝），营造安全温馨的母婴氛围',
    rhythmDescription: '舒缓柔和节奏，场景停留稍长，转场使用柔和的溶解效果',
    recommendedCaptionStyle: '圆角柔和字幕，马卡龙色衬底，圆润无衬线字体',
  },
  {
    id: 'PetFriendly',
    name: '宠物亲和风',
    nameEn: 'Pet Friendly',
    description: '可爱插画风、温暖色调，适合宠物食品、宠物用品、宠物玩具，营造陪伴和温馨感。',
    suitableCategories: ['宠物用品'],
    suitableGoals: ['种草', '促销'],
    colorTheme: { primary: '#FF7043', secondary: '#FFF3E0', accent: '#66BB6A', background: '#FFFBF5', surface: '#FFFFFF', text: '#3E2723', textSecondary: '#8D6E63' },
    typography: { ...sansSerif, titleWeight: 600 },
    visualDensity: '标准',
    motionIntensity: '标准',
    icon: '🐾',
    recommendedScenarios: ['宠物日常', '萌宠好物', '宠物喂养', '宠物健康'],
    recommendedProductTypes: ['猫粮', '狗粮', '宠物玩具', '猫砂', '宠物零食', '宠物窝'],
    recommendedVideoStructure: ['萌宠开场', '产品展示', '营养/安全卖点', '宠物使用场景', '主人好评', 'CTA'],
    recommendedCTAs: ['给毛孩最好的', '立即下单', '限时特惠', '宠爱升级'],
    colorDescription: '温暖橙色搭配自然绿色，营造活泼可爱的宠物氛围',
    rhythmDescription: '中等节奏，宠物互动场景可稍慢以展示萌态，转场柔和',
    recommendedCaptionStyle: '温暖色调字幕，圆角设计，带爪印等可爱图标',
  },
  {
    id: 'StudyOffice',
    name: '学习办公风',
    nameEn: 'Study Office',
    description: '清爽蓝绿色调、简洁排版，适合文具、办公设备、学习工具、在线课程，营造专注高效感。',
    suitableCategories: ['学习办公', '虚拟课程'],
    suitableGoals: ['讲解', '品牌'],
    colorTheme: { primary: '#1976D2', secondary: '#E3F2FD', accent: '#00BCD4', background: '#F8FBFF', surface: '#FFFFFF', text: '#1A2A3A', textSecondary: '#607D8B' },
    typography: sansSerif,
    visualDensity: '标准',
    motionIntensity: '标准',
    icon: '📚',
    recommendedScenarios: ['办公效率提升', '学习好物推荐', '课程介绍', '文具测评'],
    recommendedProductTypes: ['机械键盘', '台灯', '笔记本', '在线课程', '办公椅', '文件夹'],
    recommendedVideoStructure: ['学习/办公痛点', '产品展示', '功能/效率卖点', '使用场景', '效果对比', 'CTA'],
    recommendedCTAs: ['提升效率', '立即获取', '限时优惠', '学习升级'],
    colorDescription: '清爽蓝绿色为主，搭配白色背景，营造专注高效的学习办公氛围',
    rhythmDescription: '中等节奏，清晰有序，转场使用简洁的滑动效果',
    recommendedCaptionStyle: '清爽蓝色系字幕条，简洁无衬线字体，突出重点信息',
  },
  {
    id: 'HealthCare',
    name: '健康个护风',
    nameEn: 'Health Care',
    description: '清新医疗绿、专业感排版，适合保健品、个护产品、医疗器械、健康食品，营造专业可信感。',
    suitableCategories: ['个护健康', '食品饮料'],
    suitableGoals: ['讲解', '品牌', '种草'],
    colorTheme: { primary: '#00897B', secondary: '#E0F2F1', accent: '#26A69A', background: '#F5FFFE', surface: '#FFFFFF', text: '#1A2E2A', textSecondary: '#607D7A' },
    typography: sansSerif,
    visualDensity: '标准',
    motionIntensity: '舒缓',
    icon: '🏥',
    recommendedScenarios: ['健康科普', '个护好物', '成分解析', '使用教程'],
    recommendedProductTypes: ['电动牙刷', '按摩仪', '维生素', '护眼灯', '空气净化器', '血压计'],
    recommendedVideoStructure: ['健康痛点引入', '产品专业展示', '成分/技术讲解', '使用方法', '效果说明', 'CTA'],
    recommendedCTAs: ['关爱健康', '立即体验', '专业之选', '限时优惠'],
    colorDescription: '清新医疗绿为主，搭配白色和浅灰色，营造专业可信的健康氛围',
    rhythmDescription: '舒缓专业节奏，讲解型场景停留稍长，转场平稳',
    recommendedCaptionStyle: '绿色系字幕条，专业简洁风格，关键数据用高亮色标注',
  },
  {
    id: 'AutoGear',
    name: '汽车用品风',
    nameEn: 'Auto Gear',
    description: '深色金属质感、硬朗线条，适合车载设备、汽车配件、汽车装饰，营造专业和力量感。',
    suitableCategories: ['汽车用品'],
    suitableGoals: ['讲解', '促销'],
    colorTheme: { primary: '#F44336', secondary: '#FFEBEE', accent: '#B0BEC5', background: '#1A1A1A', surface: '#2D2D2D', text: '#F5F5F5', textSecondary: '#9E9E9E', gradient: 'linear-gradient(180deg, #1A1A1A 0%, #2D2D2D 100%)' },
    typography: boldSans,
    visualDensity: '标准',
    motionIntensity: '快节奏',
    icon: '🚗',
    recommendedScenarios: ['车载好物', '汽车改装', '驾驶体验', '车载科技'],
    recommendedProductTypes: ['车载吸尘器', '行车记录仪', '车载充电器', '汽车脚垫', '遮阳帘', '车载香薰'],
    recommendedVideoStructure: ['用车痛点场景', '产品展示', '性能参数讲解', '安装/使用演示', '效果对比', 'CTA'],
    recommendedCTAs: ['升级座驾', '立即抢购', '限时特惠', '车主必备'],
    colorDescription: '深色背景搭配红色和银色点缀，营造硬朗专业的汽车氛围',
    rhythmDescription: '快节奏动感，配合汽车感的速度切换和镜头推拉',
    recommendedCaptionStyle: '深色衬底白色粗体字幕，工业感设计，数据用红色高亮',
  },
  {
    id: 'FestivalGift',
    name: '节日礼赠风',
    nameEn: 'Festival Gift',
    description: '喜庆红色、金色点缀，适合节日礼品、礼盒套装、送礼场景，营造仪式感和情感价值。',
    suitableCategories: ['节日礼品', '食品饮料', '美妆护肤'],
    suitableGoals: ['节日营销', '促销', '品牌'],
    colorTheme: { primary: '#D32F2F', secondary: '#FFF8E1', accent: '#FFD700', background: '#FFFBF5', surface: '#FFFFFF', text: '#3E1A1A', textSecondary: '#8A6060' },
    typography: elegantSerif,
    visualDensity: '标准',
    motionIntensity: '标准',
    icon: '🎁',
    recommendedScenarios: ['节日送礼', '礼盒开箱', '送礼指南', '节日祝福'],
    recommendedProductTypes: ['月饼礼盒', '茶叶礼盒', '巧克力礼盒', '鲜花', '护肤套装', '红包套装'],
    recommendedVideoStructure: ['节日氛围开场', '礼盒精美展示', '情感卖点', '包装细节', '送礼场景', 'CTA'],
    recommendedCTAs: ['送礼首选', '立即选购', '限时礼遇', '表达心意'],
    colorDescription: '喜庆红色搭配金色点缀，营造节日仪式感和送礼氛围',
    rhythmDescription: '中等节奏，礼盒展示时稍慢以突出精致感，转场优雅',
    recommendedCaptionStyle: '红金色系字幕，优雅衬线字体，带节日元素点缀',
  },
];

/** 按 ID 获取模板家族 */
export function getFamilyById(id: string): TemplateFamily | undefined {
  return templateFamilies.find((f) => f.id === id);
}
